// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:strive_flow/domain/models/principle/principle.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(PrincipleAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(PrincipleAdapter());
  }
}
